import { Event, User, Ticket, Booking, Notification } from '../types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Jakarta Music Festival 2026',
    description: 'Indonesia\'s biggest music festival featuring international and local artists across 3 stages. Experience 24 hours of non-stop music with over 50 performances.',
    category: 'Music',
    image: 'https://picsum.photos/seed/concert1/400/600',
    price: 250,
    location: 'Gelora Bung Karno, Jakarta',
    date: '2026-03-15',
    time: '14:00',
    organizer: 'Live Nation Indonesia',
    venue: 'GBK Main Stadium',
    attendees: 45000,
    rating: 4.8,
    isFavorite: false,
    isFeatured: true,
  },
  {
    id: '2',
    title: 'TechSummit Asia 2026',
    description: 'The premier technology conference in Southeast Asia. Join 300+ speakers covering AI, blockchain, cloud computing, and the future of work.',
    category: 'Technology',
    image: 'https://picsum.photos/seed/techconf2/400/600',
    price: 350,
    location: 'Jakarta Convention Center',
    date: '2026-04-22',
    time: '09:00',
    organizer: 'TechSummit Global',
    venue: 'JCC Senayan',
    attendees: 8000,
    rating: 4.6,
    isFavorite: true,
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Bali Art Biennale',
    description: 'A curated exhibition showcasing contemporary Indonesian art alongside international installations. Featuring 120 artists from 25 countries.',
    category: 'Art',
    image: 'https://picsum.photos/seed/artexhibit3/400/600',
    price: 45,
    location: 'Museum MACAN, Bali',
    date: '2026-05-10',
    time: '10:00',
    organizer: 'Indonesia Art Foundation',
    venue: 'Museum MACAN Bali',
    attendees: 2500,
    rating: 4.7,
    isFavorite: false,
    isFeatured: true,
  },
  {
    id: '4',
    title: 'Comedy Night Live Jakarta',
    description: 'An evening of laughter with top Indonesian comedians and special international guest performers. Doors open at 6 PM.',
    category: 'Comedy',
    image: 'https://picsum.photos/seed/comedyshow4/400/600',
    price: 75,
    location: 'Balai Kartini, Jakarta',
    date: '2026-03-28',
    time: '19:00',
    organizer: 'Laugh Factory Asia',
    venue: 'Balai Kartini Grand Ballroom',
    attendees: 1200,
    rating: 4.5,
    isFavorite: false,
    isFeatured: false,
  },
  {
    id: '5',
    title: 'Jakarta Food Festival',
    description: 'Indonesia\'s largest culinary celebration with 200+ food stalls, celebrity chef demonstrations, and exclusive tasting sessions.',
    category: 'Restaurant',
    image: 'https://picsum.photos/seed/foodfest5/400/600',
    price: 35,
    location: 'Ancol, Jakarta',
    date: '2026-06-05',
    time: '11:00',
    organizer: 'Indonesian Chef Association',
    venue: 'Ancol Beach City',
    attendees: 15000,
    rating: 4.4,
    isFavorite: true,
    isFeatured: true,
  },
  {
    id: '6',
    title: 'Digital Marketing Summit',
    description: 'Learn the latest digital marketing strategies from industry leaders. Workshops, panels, and networking opportunities.',
    category: 'Business',
    image: 'https://picsum.photos/seed/bizconf6/400/600',
    price: 150,
    location: 'The Ritz-Carlton, Jakarta',
    date: '2026-04-10',
    time: '08:30',
    organizer: 'Digital Indonesia',
    venue: 'Ritz-Carlton Pacific Place',
    attendees: 600,
    rating: 4.3,
    isFavorite: false,
    isFeatured: false,
  },
  {
    id: '7',
    title: 'Bandung Electronic Music Festival',
    description: 'Three days of electronic music in the cool highlands of Bandung. International DJs and local talent on 2 stages.',
    category: 'Music',
    image: 'https://picsum.photos/seed/festival7/400/600',
    price: 180,
    location: 'Dago Pakar, Bandung',
    date: '2026-07-18',
    time: '16:00',
    organizer: 'EDM Indonesia',
    venue: 'Dago Dream Park',
    attendees: 6000,
    rating: 4.6,
    isFavorite: false,
    isFeatured: true,
  },
  {
    id: '8',
    title: 'Startup Weekend Jakarta',
    description: '54-hour event where developers, designers, and entrepreneurs come together to build innovative solutions.',
    category: 'Technology',
    image: 'https://picsum.photos/seed/startup8/400/600',
    price: 25,
    location: 'GoWork, Jakarta',
    date: '2026-05-25',
    time: '09:00',
    organizer: 'Techstars Community',
    venue: 'GoWork Pacific Place',
    attendees: 150,
    rating: 4.5,
    isFavorite: false,
    isFeatured: false,
  },
  {
    id: '9',
    title: 'Nusa Penida Beach Party',
    description: 'Beach party paradise with live DJs, fire dancers, and stunning sunset views. Limited to 2000 attendees for exclusive experience.',
    category: 'Festival',
    image: 'https://picsum.photos/seed/beachparty9/400/600',
    price: 120,
    location: 'Nusa Penida, Bali',
    date: '2026-08-12',
    time: '15:00',
    organizer: 'Bali Events Co',
    venue: 'Crystal Bay Beach',
    attendees: 2000,
    rating: 4.9,
    isFavorite: true,
    isFeatured: true,
  },
  {
    id: '10',
    title: 'Indonesian Indie Film Festival',
    description: 'Showcasing the best independent films from across the archipelago. 40 films, Q&A sessions, and industry panels.',
    category: 'Art',
    image: 'https://picsum.photos/seed/filmfest10/400/600',
    price: 55,
    location: 'CGV Grand Indonesia, Jakarta',
    date: '2026-09-20',
    time: '13:00',
    organizer: 'Indonesian Film Board',
    venue: 'CGV Grand Indonesia',
    attendees: 3000,
    rating: 4.7,
    isFavorite: false,
    isFeatured: false,
  },
  {
    id: '11',
    title: 'Bandung Jazz Festival',
    description: 'Celebrating Indonesian jazz heritage with performances from legendary and emerging jazz musicians.',
    category: 'Music',
    image: 'https://picsum.photos/seed/jazzfes11/400/600',
    price: 95,
    location: 'Gedung Sate, Bandung',
    date: '2026-10-05',
    time: '17:00',
    organizer: 'Jazz Indonesia',
    venue: 'Gedung Sate Grounds',
    attendees: 4000,
    rating: 4.8,
    isFavorite: false,
    isFeatured: false,
  },
  {
    id: '12',
    title: 'CEO Summit Bali 2026',
    description: 'Exclusive leadership summit for C-suite executives. Keynotes from global business leaders and strategic roundtables.',
    category: 'Business',
    image: 'https://picsum.photos/seed/ceosummit12/400/600',
    price: 299,
    location: 'The Mulia, Bali',
    date: '2026-11-14',
    time: '08:00',
    organizer: 'Business Leadership Forum',
    venue: 'The Mulia Resort',
    attendees: 400,
    rating: 4.9,
    isFavorite: false,
    isFeatured: true,
  },
];

export const mockUser: User = {
  id: 'user-001',
  firstName: 'John',
  lastName: 'Doe',
  email: 'john.doe@example.com',
  phone: '+62 812 3456 7890',
  avatar: 'https://picsum.photos/seed/avatar/200/200',
  interests: ['Music', 'Art', 'Technology', 'Festival'],
  notifications: true,
};

export const mockTickets: Ticket[] = [
  {
    id: 'ticket-001',
    eventId: '1',
    userId: 'user-001',
    type: 'VIP',
    price: 250,
    quantity: 2,
    seat: 'VIP-A12',
    qrCode: 'TKT-2026-JKT-MF-001',
    status: 'upcoming',
    purchaseDate: '2026-02-01',
  },
  {
    id: 'ticket-002',
    eventId: '2',
    userId: 'user-001',
    type: 'Regular',
    price: 350,
    quantity: 1,
    seat: 'B-24',
    qrCode: 'TKT-2026-JKT-TS-002',
    status: 'upcoming',
    purchaseDate: '2026-03-10',
  },
  {
    id: 'ticket-003',
    eventId: '4',
    userId: 'user-001',
    type: 'Standard',
    price: 75,
    quantity: 2,
    seat: 'C-08',
    qrCode: 'TKT-2026-JKT-CN-003',
    status: 'upcoming',
    purchaseDate: '2026-03-05',
  },
  {
    id: 'ticket-004',
    eventId: '5',
    userId: 'user-001',
    type: 'General',
    price: 35,
    quantity: 4,
    seat: 'GA-001',
    qrCode: 'TKT-2026-JKT-FF-004',
    status: 'upcoming',
    purchaseDate: '2026-04-20',
  },
  {
    id: 'ticket-005',
    eventId: '3',
    userId: 'user-001',
    type: 'Standard',
    price: 45,
    quantity: 2,
    seat: 'D-15',
    qrCode: 'TKT-2026-BLI-AB-005',
    status: 'past',
    purchaseDate: '2025-12-15',
  },
  {
    id: 'ticket-006',
    eventId: '7',
    userId: 'user-001',
    type: 'Weekend Pass',
    price: 180,
    quantity: 1,
    seat: 'GA-045',
    qrCode: 'TKT-2026-BDG-EM-006',
    status: 'cancelled',
    purchaseDate: '2026-01-20',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    title: 'Booking Confirmed',
    message: 'Your ticket for Jakarta Music Festival 2026 has been confirmed. Check your email for details.',
    time: '2026-02-01T10:30:00',
    read: true,
    type: 'booking',
    icon: 'checkmark-circle',
  },
  {
    id: 'notif-002',
    title: 'Event Reminder',
    message: 'Jakarta Music Festival 2026 starts in 3 days. Don\'t forget to bring your ID and ticket.',
    time: '2026-03-12T08:00:00',
    read: false,
    type: 'reminder',
    icon: 'alarm',
  },
  {
    id: 'notif-003',
    title: 'Special Offer',
    message: 'Get 20% off on TechSummit Asia 2026 with code TECH20. Limited time offer!',
    time: '2026-03-01T14:00:00',
    read: false,
    type: 'promotion',
    icon: 'pricetag',
  },
  {
    id: 'notif-004',
    title: 'Booking Confirmed',
    message: 'Your tickets for Comedy Night Live Jakarta are ready. See you there!',
    time: '2026-03-05T16:45:00',
    read: true,
    type: 'booking',
    icon: 'checkmark-circle',
  },
  {
    id: 'notif-005',
    title: 'Event Update',
    message: 'TechSummit Asia 2026 has added 5 new speakers. Check out the updated lineup!',
    time: '2026-03-20T09:15:00',
    read: false,
    type: 'update',
    icon: 'information-circle',
  },
  {
    id: 'notif-006',
    title: 'Payment Failed',
    message: 'Your payment for Bandung Electronic Music Festival could not be processed. Please try again.',
    time: '2026-01-25T11:30:00',
    read: true,
    type: 'error',
    icon: 'alert-circle',
  },
  {
    id: 'notif-007',
    title: 'New Events Near You',
    message: '3 new events in your area match your interests. Check them out now!',
    time: '2026-04-01T07:00:00',
    read: false,
    type: 'recommendation',
    icon: 'compass',
  },
  {
    id: 'notif-008',
    title: 'Review Request',
    message: 'How was the Bali Art Biennale? Leave a review and help others discover great events.',
    time: '2025-12-20T12:00:00',
    read: true,
    type: 'feedback',
    icon: 'chatbubble',
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'booking-001',
    eventId: '1',
    tickets: [mockTickets[0]],
    totalAmount: 500,
    paymentMethod: 'Credit Card',
    status: 'confirmed',
    date: '2026-02-01',
  },
  {
    id: 'booking-002',
    eventId: '2',
    tickets: [mockTickets[1]],
    totalAmount: 350,
    paymentMethod: 'GoPay',
    status: 'confirmed',
    date: '2026-03-10',
  },
  {
    id: 'booking-003',
    eventId: '4',
    tickets: [mockTickets[2]],
    totalAmount: 150,
    paymentMethod: 'OVO',
    status: 'confirmed',
    date: '2026-03-05',
  },
  {
    id: 'booking-004',
    eventId: '5',
    tickets: [mockTickets[3]],
    totalAmount: 140,
    paymentMethod: 'Debit Card',
    status: 'confirmed',
    date: '2026-04-20',
  },
];
