import { StyleSheet } from 'react-native';
import { fonts } from './fonts';

export const typography = StyleSheet.create({
  title: {
    fontSize: 32,
    fontWeight: '500',
    color: '#FFFFFF',
    lineHeight: 40,
    fontFamily: fonts.heading,
  },
  heading: {
    fontSize: 24,
    fontWeight: '500',
    color: '#FFFFFF',
    lineHeight: 32,
    fontFamily: fonts.heading,
  },
  subheading: {
    fontSize: 20,
    fontWeight: '500',
    color: '#FFFFFF',
    lineHeight: 28,
    fontFamily: fonts.subheading,
  },
  body: {
    fontSize: 16,
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.7)',
    lineHeight: 24,
    fontFamily: fonts.body,
  },
  bodyBold: {
    fontSize: 16,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.7)',
    lineHeight: 24,
    fontFamily: fonts.bodyBold,
  },
  caption: {
    fontSize: 13,
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.5)',
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  button: {
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
    lineHeight: 22,
    fontFamily: fonts.button,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  buttonSmall: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
    lineHeight: 20,
    fontFamily: fonts.button,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.7)',
    lineHeight: 20,
    fontFamily: fonts.body,
  },
  chip: {
    fontSize: 14,
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.6)',
    fontFamily: fonts.body,
  },
  chipActive: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
    fontFamily: fonts.body,
  },
  handle: {
    fontSize: 14,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.45)',
    fontFamily: fonts.body,
  },
  meta: {
    fontSize: 12,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.5)',
    fontFamily: fonts.body,
  },
  small: {
    fontSize: 11,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.4)',
    fontFamily: fonts.body,
  },
});
